### ISSUE TITLE
Align text to center in mobile mode

### ISSUE THREAD

**Issue by Fabian-Buitrago** [angular-medellin/website#10]
![angulamedellin6](https://user-images.githubusercontent.com/9866446/31086049-6c3775f2-a75e-11e7-9a34-b39a8c2a818e.png)

**Comment by danielcb29** [comment]
@Fabian-Buitrago are you working on this? I can start with this one ✋

**Comment by danielcb29** [comment]
Please review https://github.com/angular-medellin/website/pull/13

**Comment by Fabian-Buitrago** [comment]
nice

**Comment by jdjuan** [comment]
closed in #13
