### ISSUE TITLE
Add chat link

### ISSUE THREAD

**Issue by danielcb29** [angular-medellin/website#16]
Include Chat in menu and link it to Gitter chat

<img width="960" alt="menu" src="https://user-images.githubusercontent.com/8260962/31132897-96ee221c-a823-11e7-8410-18fd7d866a78.PNG">

**Comment by jdjuan** [comment]
I agree! 🎖 What do you say @EsneiderSM ? 👍

**Comment by EsneiderSM** [comment]
@danielcb29 @jdjuan, yes, for this release is a great idea! 👍
