### ISSUE TITLE
Add dynamic footer in the home page 🌅

### ISSUE THREAD

**Issue by jdjuan** [angular-medellin/website#4]
Add a functionality such that when you click the down arrow button, the footer shows up:

![image](https://raw.githubusercontent.com/angular-medellin/website/master/design/Desktop/1-Home.jpg)

![image2](https://raw.githubusercontent.com/angular-medellin/website/master/design/Desktop/2-Footer-Up.jpg)

**Comment by Fabian-Buitrago** [comment]
I want to work on this functionality :fire:

**Comment by jdjuan** [comment]
I think this is already finished! 😎 see angularmedellin.com
