### ISSUE TITLE
Modify size of the subscription input to receive news 

### ISSUE THREAD

**Issue by Fabian-Buitrago** [angular-medellin/website#7]
![angulamedellin2](https://user-images.githubusercontent.com/9866446/31084846-265f00de-a75b-11e7-9b04-ad08095bce4b.png)

**Comment by danielcb29** [comment]
@Fabian-Buitrago you mean, set input size as button size?

**Comment by Fabian-Buitrago** [comment]
The idea is that the input has the same size as the button

**Comment by danielcb29** [comment]
Nice

**Comment by EsneiderSM** [comment]
Please, check the PR #15
