### ISSUE TITLE
Hide social media container when the footer is visible

### ISSUE THREAD

**Issue by Fabian-Buitrago** [angular-medellin/website#8]
![angulamedellin3](https://user-images.githubusercontent.com/9866446/31084994-919c5b76-a75b-11e7-8c33-a8af450d4d04.png)

**Comment by danielcb29** [comment]
I can take this one ✋

**Comment by Fabian-Buitrago** [comment]
You can take, no problem

**Comment by danielcb29** [comment]
Please review https://github.com/angular-medellin/website/pull/14
